name: 🐞 Issue report
description: Report an issue in Manga Akojdad
labels: [Bug]
body:
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue in Manga Akojdad.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen in Manga Akojdad.
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens in Manga Akojdad.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true
  # باقي النموذج كما هو، مع تعديل "Mihon" إلى "Manga Akojdad"